"""empty message

Revision ID: 2e25758e2f41
Revises: 654c3f707cbf
Create Date: 2024-10-10 16:01:12.291131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e25758e2f41'
down_revision = '654c3f707cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_phone', type_='foreignkey')
        batch_op.drop_column('user_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_user_phone', 'user', ['user_phone'], ['user_phone'])

    # ### end Alembic commands ###
