"""empty message

Revision ID: 4743a254b730
Revises: 78b0bcb60acf
Create Date: 2024-10-04 17:48:47.289274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4743a254b730'
down_revision = '78b0bcb60acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_photo', sa.String(), nullable=False, server_default='default.png'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_photo')

    op.drop_table('order')
    # ### end Alembic commands ###
